### ISSUE TITLE
Picture can't keep ratio 1:1

### ISSUE THREAD

**Issue by doanyennhi** [kuri-team/yabe-mall#42]
Profile picture on My Account page can't keep ratio 1:1

**To Reproduce**
1. Go to Register
2. Upload profile picture and fill out the entire form
3. Click "REGISTER" 
4. Login with information used in register. If login is successful, it will redirect to My Account page

**Expected behavior**
My Account page: The profile picture should have ratio of 1:1.

**Comment by miketvo** [comment]
RESOLVED
